db:
  image: postgres
  ports:
     - "5432:5432"
  environment:
    - POSTGRES_USER=ticketmonster
    - POSTGRES_PASSWORD=ticketmonster-docker
modcluster:
  container_name: "modcluster"
  image: rafabene/mod_cluster
  ports:
     - "80:80"
wildfly:
  #image: rafabene/wildfly-ticketmonster
  build: ../Dockerfiles/ticketmonster/
  links:
    - db
    - modcluster
